Test SSH

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -65,6 +65,13 @@ jobs:
     needs: CI
 
     steps:
+      - name: Verify SSH Configuration
+        run: |
+          echo "Using SSH Host: ${{ secrets.SSH_HOST }}"
+          echo "Using SSH Port: ${{ secrets.SSH_PORT }}"
+          # Test SSH connection
+          ssh -i $HOME/.ssh/id_rsa -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo 'SSH Connection Successful'" || echo "SSH Connection Failed"
+
       - name: Deploy to Remote Server
         uses: appleboy/ssh-action@v0.1.4
         with:
@@ -72,7 +79,6 @@ jobs:
           port: ${{ secrets.SSH_PORT }}
           username: ${{ secrets.SSH_USER }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
-          debug: true
           envs: |
             DOCKER_IMAGE=ghcr.io/augisbud/quizcraft/backend:latest
           script: |
